# Generated by Django 5.0.13 on 2025-03-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_rename_visit_pagevisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagevisit',
            name='path',
            field=models.CharField(max_length=255),
        ),
    ]
